#! /bin/sh

battery () {
    echo "---------- Battery ----------"
    for bat in $(cat /sys/class/power_supply/BAT*/capacity); do
        echo "Battery level: " $bat "%"
    done
    echo "----------------------------"

}

clock () {
    while true; do
        clear
        echo "==========="
        date +"%r"
        echo "==========="
        sleep 1
    done
}
