#! /bin/sh

# General ---------------------------------------------------------------------

# History
alias h='history'
alias hg='history|grep '

# ls
alias la='ls -A'

# System ----------------------------------------------------------------------

# Arch
alias suspend="systemctl suspend"

alias autoremove="sudo pacman -Qtdq | sudo pacman -Rns -"

# xdg
alias open="xdg-open"

# Sound
alias pm='pulsemixer'

# chezmoi ---------------------------------------------------------------------

alias cz='chezmoi'

# Python ----------------------------------------------------------------------

# pipenv
alias pips='pipenv shell'
alias pipi='pipenv install'
alias pipc='pipenv clean'
alias pipg='pipenv graph'
alias pipu='pipenv uninstall'

# Git -------------------------------------------------------------------------

# basics
alias gf='git fetch'
alias gp='git pull'
alias ga='git add'
alias gC='git commit'
alias gc='git checkout'
alias gP='git push'
alias gs='git status'
alias gl='git log'
alias gd='git diff'
alias gr='git restore'
alias gR='git reset'
alias gb='git branch'

