#! /bin/sh

math() {
    echo $(( $* ))
}

battery () {
    echo "---------- Battery ----------"
    for bat in $(cat /sys/class/power_supply/BAT*/capacity); do
        echo "Battery level: " $bat "%"
    done
    echo "----------------------------"

}

clock () {
    while true; do
        clear
        echo "==========="
        date +"%r"
        echo "==========="
        sleep 1
    done
}

remindme () {
    echo FUNCTIONS
    echo ---------
    echo math - simple calculator
    echo battery - display battery information
    echo clock - display the time

    echo \n

    echo APPLICATIONS
    echo ------------
    echo Normal linux stuff:
    echo "  " pkill - look up, signal, or wait for processes based on name and other attributes
    echo "  " pstree - display a tree of processes
    echo "  " lsblk - disk memory info
    echo "  " whoami - print effective userid
    echo "  " which - shows the full path of shell commands
    echo "  " whatis - display one-line manual page descriptions
    echo "  " whereis - locate the binary, source, and manual page files for a command
    echo System monitor and management:
    echo "  " glances, htop - system monitoring
    echo "  " alsamixer, pulsemixer - audio control
    echo Editing:
    echo "  " tokei - file analysis, lines of code
    echo "  " bat - better cat
    echo "  " rg - better grep
    echo Apps:
    echo "  " spt - spotify TUI
    echo "  " nmtui - network manager TUI
    echo "  " nitrogen - manage wallpapers
    echo "  " nnn - file explorer
    echo "  " pdfgrep, pdftotext - convert and search pdfs
}
