#! /bin/sh

PLUG_DIR=$XDG_DATA_HOME/zsh/plugins

if [ ! -d PLUG_DIR ]; then
    mkdir -p "$XDG_DATA_HOME"
fi

zplg() {

    if [ $1 = "add" ]; then

        # 0     1   2                   3
        # zplg  add <github usr/repo>   <zsh-file>

        target=$PLUG_DIR/$(cut -d '/' -f2 <<< $2)

        if [ ! -d "$target" ]; then
            git clone "https://github.com/$2" $target
        fi

        if [ ! -e "$target/$3" ]; then
            printf '%s\n' "Plugin file \"$3\" not found in repository \"$target\"" >&2
        else
            source $target/$3
        fi

    elif [ $1 = "del" ]; then

        # 0     1   2
        # zplg  del <repo>

        if [ -d "$PLUG_DIR/$2" ]; then
            rm -rf "$PLUG_DIR/$2"
        fi

    elif [ $1 = "update" ]; then

        # 0     1   2
        # zplg  del [ all | <repo> ]

        if [ $2 = "all" ]; then
            for repo in $PLUG_DIR/*; do
                ( cd $repo && git pull )
            done
        elif [ -e "$PLUG_DIR/$2" ]; then
            ( cd "$PLUG_DIR/$2" && git pull )
        fi

    fi

}

