
format = """\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
$username\
$hostname\
$python\
$character\
"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[git_branch]
format = "[$symbol$branch]($style) "

[python]
format = '[${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
